### ISSUE TITLE
Crear atomo Image

### ISSUE THREAD

**Issue by 9gustin** [frontendcafe/cmyk-sunset#38]
Se debe hacer en la app de React. Revisar variantes y estilos en [FIgma](https://www.figma.com/file/BE4Op1kTtswY2CyRARcXLz/Grupo-4---Proyecto-Marvel-Ecommerce?node-id=88%3A17)

Agregar html5 prop para lazy load de la imagen

Esta card incluye solo el maquetado del componente.

**Comment by fernandoarmonellifiedler** [comment]
La puedo agarrar a esta pero tengo una duda: 
¿Que seria "Agregar html5 prop para lazy load de la imagen"?
